"""Parameter mapping between CMA-ES latent vectors and atomic_solver TOML."""

import math
from collections import OrderedDict

# Piece values are kept fixed for the first tuning pass.
PIECES = OrderedDict([
    ("pawn", 100),
    ("knight", 320),
    ("bishop", 330),
    ("rook", 500),
    ("queen", 900),
    ("commoner", 20_000),
])

# Sensible first subset: all non-piece ScorerParams fields.
# score_winning_capture and score_promotion are intentionally fixed in this pass
# because they are huge, almost-categorical thresholds; tuning them safely
# requires extra hierarchy care that is deferred.
SCORER_DEFAULTS = OrderedDict([
    ("score_capture", 5_000),
    ("capture_net_scale", 10),
    ("score_threat_last", 10_000),
    ("score_threat", 1_000),
    ("score_kamikaze_last", 9_000),
    ("score_kamikaze", 3_000),
    ("score_approach", 100),
    ("score_approach_step", 10),
    ("score_center", 50),
    ("score_center_step", 10),
    ("score_pawn_storm", 5_500),
    ("score_pawn_storm_step", 100),
    ("score_rook_center", 500),
    ("score_rook_open_file", 2_000),
    ("score_rook_open_file_step", 50),
    ("score_rook_back_rank", 300),
    ("and_pawn_storm_scale", 50),
    ("and_rook_attack_scale", 50),
    ("and_approach_scale", 75),
])

# Fixed thresholds from the default config.
SCORE_PROMOTION = 1_000_000
SCORE_WINNING_CAPTURE = 100_000_000

# Prevent overflow in the solver's i32 computations and in derived hierarchy checks.
MAX_COMPONENT = 10_000_000
MAX_I32 = 2_147_483_647

# Net material destroyed in the maximum non-winning capture:
# removing every non-commoner enemy piece with a pawn.
MAX_NON_COMMONER_VALUE = PIECES["queen"] + PIECES["rook"] + PIECES["bishop"] + PIECES["knight"]
MAX_CAPTURE_NET = MAX_NON_COMMONER_VALUE - PIECES["pawn"]


def decode(x):
    """Map a latent CMA-ES vector to a valid ScorerParams dict.

    Returns None if the vector cannot be mapped to a valid config (overflow or
    unsatisfiable hierarchy).
    """
    if len(x) != len(SCORER_DEFAULTS):
        raise ValueError(f"latent vector length {len(x)} != {len(SCORER_DEFAULTS)}")

    raw = {}
    for i, (name, default) in enumerate(SCORER_DEFAULTS.items()):
        xi = x[i]
        v = round(default * math.exp(xi))
        if name.startswith("and_"):
            # Percent scale in [0, 100].
            v = min(100, max(0, v))
        else:
            # Clamp to a safe range to avoid i32 overflow in quiet-move sums.
            v = min(max(v, 0), MAX_COMPONENT)
        raw[name] = v

    # Enforce capture < promotion hierarchy by scaling both capture params.
    score_capture = raw["score_capture"]
    capture_net_scale = raw["capture_net_scale"]
    max_capture_score = score_capture + capture_net_scale * MAX_CAPTURE_NET
    if max_capture_score >= SCORE_PROMOTION:
        factor = (SCORE_PROMOTION - 1) / max_capture_score
        score_capture = int(score_capture * factor)
        capture_net_scale = int(capture_net_scale * factor)
        max_capture_score = score_capture + capture_net_scale * MAX_CAPTURE_NET

    if max_capture_score >= SCORE_PROMOTION or max_capture_score > MAX_I32:
        return None

    raw["score_capture"] = score_capture
    raw["capture_net_scale"] = capture_net_scale

    # Add fixed hierarchy fields.
    raw["score_promotion"] = SCORE_PROMOTION
    raw["score_winning_capture"] = SCORE_WINNING_CAPTURE

    # Final overflow safety check.
    for k, v in raw.items():
        if not isinstance(v, int):
            v = int(round(v))
        if v < 0 or v > MAX_I32:
            return None
        raw[k] = v

    return raw


def encode(params):
    """Inverse: map a raw params dict back to a latent vector (best-effort).

    Missing keys default to the current SCORER_DEFAULTS value (latent 0.0).
    Extra keys are ignored so an older config can seed a newer parameter set.
    """
    x = []
    for name, default in SCORER_DEFAULTS.items():
        v = params.get(name, default)
        if v is None:
            v = default
        try:
            v = float(v)
        except (TypeError, ValueError):
            v = float(default)
        if v <= 0:
            x.append(-10.0)
        else:
            x.append(math.log(v / default))
    return x


def write_toml(params, path):
    """Write a partial [scorer] TOML file; missing keys use compiled-in defaults."""
    with open(path, "w") as f:
        f.write("# Generated by CMA-ES tuner\n")
        f.write("[scorer]\n")
        for name, value in params.items():
            # Only write the subset we are tuning; the Rust side uses serde(default).
            if not name.startswith("pieces."):
                f.write(f"{name} = {value}\n")
        f.write("\n[scorer.pieces]\n")
        for name, value in PIECES.items():
            f.write(f"{name} = {value}\n")
